### ISSUE TITLE
TerritoriesConfig

### ISSUE THREAD

**Issue by Nickle-Eye** [Omega-Corp-myDU/changelog#1]
### Old 

``` yaml
TerritoriesConfig:
  parent: FeaturesConfig
  territoryUnitDeployDuration: 300
  territoryUnitRetrieveCooldown: 604800
  orgFirstTerritoryFee: 10000
  orgTerritoryFeeFactor: 30000
  orgTerritoryFeeExponant: 0
  playerFirstTerritoryFee: 0
  playerTerritoryFeeFactor: 0
  playerTerritoryFeeExponant: 0
  initialExpirationDelayDays: 3
  maxBalanceInFeeDays: 91
  requisitionDelayDays: 15
  upkeepIntervalDays: 30
  upkeepFee: 1000
```

### New 

``` yaml
TerritoriesConfig:
  parent: FeaturesConfig
  territoryUnitDeployDuration: 10
  territoryUnitRetrieveCooldown: 604800
  orgFirstTerritoryFee: 5
  orgTerritoryFeeFactor: 5
  orgTerritoryFeeExponant: 0
  playerFirstTerritoryFee: 0
  playerTerritoryFeeFactor: 55
  playerTerritoryFeeExponant: 0
  initialExpirationDelayDays: 3
  maxBalanceInFeeDays: 91
  requisitionDelayDays: 14
  upkeepIntervalDays: 365
  upkeepFee: 0
```
