### ISSUE TITLE
Mining Unit Large

### ISSUE THREAD

**Issue by Nickle-Eye** [Omega-Corp-myDU/changelog#2]
### (OLD)

``` yaml
MiningUnitLarge1:
  displayName: Basic Mining Unit
  scale: l
  level: 1
  parent: MiningUnit
  oreTier: 1
  maxMiningRate: 100
  miningEfficiency: 0.9
  unitMass: 5131
  unitVolume: 2200
  hitpoints: 11250

MiningUnitLarge2:
  displayName: Uncommon Mining Unit
  scale: l
  level: 2
  parent: MiningUnit
  oreTier: 2
maxMiningRate: 100
  miningEfficiency: 0.9
  unitMass: 5160
  unitVolume: 2454
  hitpoints: 11250

MiningUnitLarge3:
  displayName: Advanced Mining Unit
  scale: l
  level: 3
  parent: MiningUnit
  oreTier: 3
  maxMiningRate: 100
  miningEfficiency: 0.9
  unitMass: 7500
  unitVolume: 4050
  hitpoints: 11250

MiningUnitLarge4:
  displayName: Rare Mining Unit
  scale: l
  level: 4
  parent: MiningUnit
  oreTier: 4
  maxMiningRate: 100
  miningEfficiency: 0.9
  unitMass: 7800
  unitVolume: 4200
  hitpoints: 11250

MiningUnitLarge5:
  displayName: Exotic Mining Unit
  scale: l
  level: 5
  parent: MiningUnit
  oreTier: 5
  maxMiningRate: 100
  miningEfficiency: 0.9
  unitMass: 8500
  unitVolume: 4400
  hitpoints: 11250
```

### (NEW)

``` yaml
MiningUnitLarge1:
  displayName: Basic Mining Unit
  scale: l
  level: 1
  parent: MiningUnit
  oreTier: 1
  maxMiningRate: 500
  miningEfficiency: 10
  unitMass: 5131
  unitVolume: 2200
  hitpoints: 11250

MiningUnitLarge2:
  displayName: Uncommon Mining Unit
  scale: l
  level: 2
  parent: MiningUnit
  oreTier: 2
  maxMiningRate: 500
  miningEfficiency: 10
  unitMass: 5160
  unitVolume: 2454
  hitpoints: 11250

MiningUnitLarge3:
  displayName: Advanced Mining Unit
  scale: l
  level: 3
  parent: MiningUnit
  oreTier: 3
  maxMiningRate: 500
  miningEfficiency: 10
  unitMass: 7500
  unitVolume: 4050
  hitpoints: 11250

MiningUnitLarge4:
  displayName: Rare Mining Unit
  scale: l
  level: 4
  parent: MiningUnit
  oreTier: 4
  maxMiningRate: 500
  miningEfficiency: 10
  unitMass: 7800
  unitVolume: 4200
  hitpoints: 11250

MiningUnitLarge5:
  displayName: Exotic Mining Unit
  scale: l
  level: 5
  parent: MiningUnit
  oreTier: 5
  maxMiningRate: 500
  miningEfficiency: 10
  unitMass: 8500
  unitVolume: 4400
  hitpoints: 11250
```
