### ISSUE TITLE
Reduced Repair Unit times

### ISSUE THREAD

**Issue by ZomecGaming** [Omega-Corp-myDU/changelog#22]
### Default Values

``` yaml
Will get from my server
```

### New Values

``` yaml
RepairUnit:
  parent: CombatDefense
  displayName: Maintenance Unit
  description: Maintenance Units can repair and reset Constructs, based on saved snapshots. They can also dismantle Constructs.
  isUseable: true
  repairDuration16m: 300
  repairDuration32m: 600
  repairDuration64m: 1200
  repairDuration128m: 1500
  unitMass: 25590
  unitVolume: 4366
  scale: xl
  level: 3
  visibilityLOD: 4
```
