### ISSUE TITLE
Created a working XL Static Core

### ISSUE THREAD

**Issue by ZomecGaming** [Omega-Corp-myDU/changelog#24]
# What does the change effect:
New Toy!

# Archive of Changes

## New  Values
``` yaml

CoreUnitStatic512Omega:
  parent: CoreUnitStatic
  constructSize: 512
  assetAlias: CoreUnitStatic512
  displayName: Static Core Unit
  scale: xl
  newPlayerDefaultQty: 0
  cellSize: 0.25
  unitVolume: 2869.00
  unitMass: 13141.47
  level: 4
  price: 667
  requiredTalents:
  - name: StaticCoreUnitExpertise
    level: 5
  hitpoints: 11541

```

# Any other note about this change that is relevant:
Describe the note here
