### ISSUE TITLE
Create an XL Space Core Unit

### ISSUE THREAD

**Issue by ZomecGaming** [Omega-Corp-myDU/changelog#25]
# What does the change effect:
New Space Core Unit

# Archive of Changes

## New  Values
``` yaml

CoreUnitSpace512Locura:
  parent: CoreUnitSpace
  constructSize: 512
  assetAlias: CoreUnitSpace256
  displayName: Space Core Unit
  unitVolume: 2869.00
  unitMass: 13141.47
  level: 4
  scale: xl
  hitpoints: 11541
  cellSize: 0.25
  requiredTalents:
  - name: SpaceCoreUnitExpertise
    level: 5

```

# Any other note about this change that is relevant:
Describe the note here
