### ISSUE TITLE
Mining Unit Small

### ISSUE THREAD

**Issue by Nickle-Eye** [Omega-Corp-myDU/changelog#3]
### (Old Values) 

``` yaml
MiningUnitSmall1:
  displayName: Basic Mining Unit
  scale: s
  level: 1
  parent: MiningUnit
  oreTier: 1
  maxMiningRate: 50
  miningEfficiency: 0.7
  unitMass: 180
  unitVolume: 70
  hitpoints: 2500
  newPlayerDefaultQty: 0
```

### (New Values) 

``` yaml
MiningUnitSmall1:
  displayName: Basic Mining Unit
  scale: s
  level: 1
  parent: MiningUnit
  oreTier: 1
  maxMiningRate: 500
  miningEfficiency: 100
  unitMass: 180
  unitVolume: 70
  hitpoints: 2500
  newPlayerDefaultQty: 0
```
