### ISSUE TITLE
Mining Unit Tweaks

### ISSUE THREAD

**Issue by ZomecGaming** [Omega-Corp-myDU/changelog#35]
# What does the change effect:
Speeds

# Archive of Changes

## Default Values
``` yaml

MiningUnit:
  parent: IndustryInfrastructure
  displayName: Mining units
  description: Mining Units can be deployed on constructs in appropriate territories in order to extract raw ore from territory tiles. Mining units will need to be regularly calibrated for optimal usage.
  visibilityLOD: 4
  calibrationGracePeriodHours: 72
  isUseable: true
  calibrationDecreaseRatePerHour: 0
  calibrationCooldownHour: 24
  adjacentTerritoryBonus: 0.1
  runtimeHours: 1

```

## New  Values
``` yaml

MiningUnit:
  parent: IndustryInfrastructure
  displayName: Mining units
  description: Mining Units can be deployed on constructs in appropriate territories in order to extract raw ore from territory tiles. Mining units will need to be regularly calibrated for optimal usage.
  visibilityLOD: 4
  calibrationGracePeriodHours: 72
  isUseable: true
  calibrationDecreaseRatePerHour: 0
  calibrationCooldownHour: 0
  adjacentTerritoryBonus: 0.1
  runtimeHours: .5
  pickupCooldownHour: 0
  stopCooldownHour: 0

```

# Any other note about this change that is relevant:
Describe the note here
