### ISSUE TITLE
Construct Speed Config

### ISSUE THREAD

**Issue by Nickle-Eye** [Omega-Corp-myDU/changelog#4]
### Default Values

``` yaml
ConstructSpeedConfig:
  parent: FeaturesConfig
  heavyConstructMass: 3000000
  maxHeavyLinearSpeedKmH: 20000
  maxHeavyAngularSpeed: 0.1
  lightConstructMass: 10000
  maxLightLinearSpeedKmH: 50000
  maxLightAngularSpeed: 3
  convexity: 3.5
  convergenceDuration: 10
  useAtmoSpeedLimit: false
  useRelativisticMassIncrease: false
```

### New Values

``` yaml
ConstructSpeedConfig:
  parent: FeaturesConfig
  heavyConstructMass: 3000000
  maxHeavyLinearSpeedKmH: 85000
  maxHeavyAngularSpeed: 0.1
  lightConstructMass: 10000
  maxLightLinearSpeedKmH: 125000
  maxLightAngularSpeed: 3
  convexity: 3.5
  convergenceDuration: 10
  useAtmoSpeedLimit: false
  useRelativisticMassIncrease: false
```
