### ISSUE TITLE
Programing Board Links

### ISSUE THREAD

**Issue by majestic44** [Omega-Corp-myDU/changelog#6]
Updated number of links possible to Programming Board.

### Default Values
``` yaml
ProgrammingBoard:
  parent: Generic
  displayName: Programming board
  description: Programming boards can be used to house Lua functions.
  unitMass: 27.74
  unitVolume: 12.70
  level: 1
  scale: xs
  hitpoints: 50
```
### New Values
``` yaml
ProgrammingBoard:
  parent: Generic
  displayName: Programming board
  description: Programming boards can be used to house Lua functions.
  unitMass: 27.74
  unitVolume: 12.70
  level: 1
  scale: xs
  hitpoints: 50
  nbControlPlugOut: 20
```
