### ISSUE TITLE
ContainerHUB Links

### ISSUE THREAD

**Issue by majestic44** [Omega-Corp-myDU/changelog#7]
Updated the number of links to and from ContainerHUB from `10 IN and 10 OUT` to `40 IN and 40 OUT`

### Default Values
``` yaml
ContainerHub:
  parent: ItemContainer
  displayName: Container Hub
  description: A Container Hub allows you to link several containers together and access them as if they were only one.
  maxVolume: 0
  unitVolume: 44.30
  unitMass: 55.80
  level: 3
  scale: xs
  nbItemPlugIn: 10
  hitpoints: 50
  visibilityLOD: 0
```

### New Values
``` yaml
ContainerHub:
  parent: ItemContainer
  displayName: Container Hub
  description: A Container Hub allows you to link several containers together and access them as if they were only one.
  maxVolume: 0
  unitVolume: 44.30
  unitMass: 55.80
  level: 3
  scale: xs
  nbItemPlugIn: 10
  hitpoints: 50
  visibilityLOD: 0
  nbIndustryPlugIn: 40
  nbIndustryPlugOut: 40
```
